name: Project Tests
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.2
      - name: Run
        run: |
          python -m pip install virtualenv
          python -m venv venv/
          python -m pip install --upgrade pip
          source venv/bin/activate
          pip install -r requirements.txt
          mkdir assets/
          python refresh_data.py
          pytest -vv
